import type { ActivityType, DailyTarget, Goal, PracticeSession, QuizQuestion, RoleType, SyllabusTopic, TimeBlock } from "./types";

export const activityMeta: Record<
  ActivityType,
  { label: string; color: string; soft: string; border: string; targetHours: number }
> = {
  football: {
    label: "Football",
    color: "#2c9b58",
    soft: "#eaf7ee",
    border: "#94d3aa",
    targetHours: 5,
  },
  school: {
    label: "School Work",
    color: "#2166b5",
    soft: "#edf5ff",
    border: "#9fc8f8",
    targetHours: 10,
  },
  cadets: {
    label: "Air Cadets",
    color: "#0a457a",
    soft: "#eaf2fa",
    border: "#96b9d8",
    targetHours: 4,
  },
  priority: {
    label: "Priority",
    color: "#f08a15",
    soft: "#fff3e3",
    border: "#fac77f",
    targetHours: 2,
  },
  other: {
    label: "Other",
    color: "#8a96a3",
    soft: "#f3f5f7",
    border: "#cbd2da",
    targetHours: 3,
  },
};

export const weekDays = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];

export const roleMeta: Record<RoleType, { label: string; activity: ActivityType; success: string }> = {
  student: {
    label: "Student",
    activity: "school",
    success: "revision and exam confidence",
  },
  corporal: {
    label: "Corporal",
    activity: "cadets",
    success: "leadership and teaching capability",
  },
  goalkeeper: {
    label: "Goalkeeper",
    activity: "football",
    success: "matchday consistency",
  },
};

export const defaultBlocks: TimeBlock[] = [
  {
    id: "school-mon",
    title: "School",
    detail: "Lessons and tutor time",
    activity: "school",
    day: 0,
    start: 510,
    end: 915,
  },
  {
    id: "algebra-mon",
    title: "Maths - Algebra",
    detail: "Linear equations set",
    activity: "priority",
    day: 0,
    start: 960,
    end: 1020,
  },
  {
    id: "training-mon",
    title: "Football Training",
    detail: "Technical and fitness",
    activity: "football",
    day: 0,
    start: 1050,
    end: 1140,
  },
  {
    id: "cadets-mon",
    title: "Air Cadets Drill",
    detail: "Parade practice",
    activity: "cadets",
    day: 0,
    start: 1155,
    end: 1215,
  },
  {
    id: "school-tue",
    title: "School",
    detail: "Lessons and tutor time",
    activity: "school",
    day: 1,
    start: 510,
    end: 915,
  },
  {
    id: "science-tue",
    title: "Science Homework",
    detail: "Forces worksheet",
    activity: "school",
    day: 1,
    start: 960,
    end: 1020,
  },
  {
    id: "skills-tue",
    title: "Football Skills",
    detail: "First touch and passing",
    activity: "football",
    day: 1,
    start: 1050,
    end: 1125,
  },
  {
    id: "school-wed",
    title: "School",
    detail: "Lessons and tutor time",
    activity: "school",
    day: 2,
    start: 510,
    end: 915,
  },
  {
    id: "essay-wed",
    title: "English Essay",
    detail: "Paragraph structure",
    activity: "school",
    day: 2,
    start: 960,
    end: 1020,
  },
  {
    id: "gym-wed",
    title: "Gym / Fitness",
    detail: "Mobility and strength",
    activity: "football",
    day: 2,
    start: 1050,
    end: 1110,
  },
  {
    id: "homework-wed",
    title: "Homework",
    detail: "Review notes",
    activity: "school",
    day: 2,
    start: 1140,
    end: 1200,
  },
  {
    id: "revision-thu",
    title: "Revision",
    detail: "Flashcards",
    activity: "school",
    day: 3,
    start: 450,
    end: 495,
  },
  {
    id: "school-thu",
    title: "School",
    detail: "Lessons and tutor time",
    activity: "school",
    day: 3,
    start: 510,
    end: 915,
  },
  {
    id: "maths-practice-thu",
    title: "Maths Practice",
    detail: "Algebra questions",
    activity: "school",
    day: 3,
    start: 960,
    end: 1020,
  },
  {
    id: "match-prep-thu",
    title: "Football Match Prep",
    detail: "Set-piece review",
    activity: "football",
    day: 3,
    start: 1050,
    end: 1110,
  },
  {
    id: "tactics-thu",
    title: "Tactics Review",
    detail: "Shape and pressing",
    activity: "cadets",
    day: 3,
    start: 1140,
    end: 1185,
  },
  {
    id: "school-fri",
    title: "School",
    detail: "Lessons and tutor time",
    activity: "school",
    day: 4,
    start: 510,
    end: 915,
  },
  {
    id: "history-fri",
    title: "History Notes",
    detail: "Source summary",
    activity: "school",
    day: 4,
    start: 960,
    end: 1020,
  },
  {
    id: "match-sat",
    title: "Football Match",
    detail: "Arrive 30 mins early",
    activity: "football",
    day: 5,
    start: 540,
    end: 660,
  },
  {
    id: "study-sat",
    title: "Study Block",
    detail: "Maths and science",
    activity: "school",
    day: 5,
    start: 720,
    end: 810,
  },
  {
    id: "cadets-sat",
    title: "Air Cadets Training",
    detail: "Leadership tasks",
    activity: "cadets",
    day: 5,
    start: 960,
    end: 1080,
  },
  {
    id: "review-sun",
    title: "Weekly Review",
    detail: "Plan next week",
    activity: "school",
    day: 6,
    start: 720,
    end: 780,
  },
  {
    id: "activity-sun",
    title: "Air Cadets Activity",
    detail: "Navigation basics",
    activity: "cadets",
    day: 6,
    start: 1020,
    end: 1140,
  },
  {
    id: "plan-sun",
    title: "Plan Next Week",
    detail: "Goals and kit list",
    activity: "priority",
    day: 6,
    start: 1200,
    end: 1230,
  },
];

export const defaultGoals: Goal[] = [
  {
    id: "fitness",
    title: "Improve Match Fitness",
    activity: "football",
    targetDate: "30 Jul 2026",
    progress: 80,
    nextStep: "Complete two high-intensity sessions this week.",
  },
  {
    id: "maths",
    title: "Maths - Grade A Target",
    activity: "school",
    targetDate: "18 Jul 2026",
    progress: 65,
    nextStep: "Answer 20 algebra questions without notes.",
  },
  {
    id: "drill",
    title: "Air Cadets - Drill Standard",
    activity: "cadets",
    targetDate: "31 Aug 2026",
    progress: 75,
    nextStep: "Practise halt, turn, and salute sequence.",
  },
];

export const defaultDailyTargets: DailyTarget[] = [
  {
    id: "target-exam-stock",
    title: "Add 2 exam questions",
    activity: "school",
    role: "student",
    measure: "Include mark-scheme notes",
    done: false,
  },
  {
    id: "target-drill",
    title: "Practise drill commands",
    activity: "cadets",
    role: "corporal",
    measure: "One clean halt-turn-salute sequence",
    done: false,
  },
  {
    id: "target-keeper",
    title: "Complete handling reps",
    activity: "football",
    role: "goalkeeper",
    measure: "20 catches, 10 low saves",
    done: false,
  },
];

export const defaultPracticeSessions: PracticeSession[] = [
  {
    id: "practice-drill-command",
    title: "Drill Command Sequence",
    activity: "cadets",
    role: "corporal",
    focus: "Timing, voice projection, halt-turn-salute",
    durationMinutes: 30,
    confidence: 70,
  },
  {
    id: "practice-leadership-brief",
    title: "Leadership Brief",
    activity: "cadets",
    role: "corporal",
    focus: "Set task, check understanding, debrief cadets",
    durationMinutes: 25,
    confidence: 62,
  },
  {
    id: "practice-goalkeeper-handling",
    title: "Goalkeeper Handling",
    activity: "football",
    role: "goalkeeper",
    focus: "Clean catch, set position, quick reset",
    durationMinutes: 45,
    confidence: 76,
  },
  {
    id: "practice-goalkeeper-distribution",
    title: "Distribution Under Pressure",
    activity: "football",
    role: "goalkeeper",
    focus: "Scanning, first touch, pass accuracy",
    durationMinutes: 35,
    confidence: 68,
  },
  {
    id: "practice-exam-answering",
    title: "Exam Answer Practice",
    activity: "school",
    role: "student",
    focus: "Plan answer, write response, self-mark",
    durationMinutes: 40,
    confidence: 64,
  },
];

export const defaultSyllabus: SyllabusTopic[] = [
  {
    id: "maths-algebra",
    title: "Maths - Algebra",
    activity: "school",
    area: "Linear equations, sequences",
    progress: 72,
    knowledge: [
      "Balance both sides of an equation when isolating a variable.",
      "Substitute values back into the original equation to check answers.",
      "For arithmetic sequences, identify the common difference first.",
    ],
  },
  {
    id: "science-physics",
    title: "Science - Physics",
    activity: "school",
    area: "Forces and motion",
    progress: 58,
    knowledge: [
      "Resultant force is the overall force after combining all forces.",
      "Speed equals distance divided by time.",
      "A flat section on a distance-time graph means the object is stationary.",
    ],
  },
  {
    id: "english-writing",
    title: "English - Writing",
    activity: "school",
    area: "Essay structure, analysis",
    progress: 64,
    knowledge: [
      "Start a paragraph with a clear point linked to the question.",
      "Use evidence precisely and explain how it supports the point.",
      "Close by connecting the analysis back to the argument.",
    ],
  },
  {
    id: "cadets-nav",
    title: "Air Cadets - Navigation",
    activity: "cadets",
    area: "Map symbols, bearings",
    progress: 61,
    knowledge: [
      "Grid references read eastings first, then northings.",
      "A bearing is measured clockwise from north.",
      "Use contour lines to judge slope and height change.",
    ],
  },
  {
    id: "football-game",
    title: "Football - Match Craft",
    activity: "football",
    area: "Positioning, scanning",
    progress: 69,
    knowledge: [
      "Scan before receiving to choose the next action earlier.",
      "Create passing angles by moving off the marker's line.",
      "Recover goal-side quickly after losing possession.",
    ],
  },
];

export const defaultQuestions: QuizQuestion[] = [
  {
    id: "q-algebra-1",
    topicId: "maths-algebra",
    prompt: "What is the solution to 2x + 5 = 15?",
    options: ["x = 3", "x = 5", "x = 10", "x = 20"],
    answer: 1,
    explanation: "Subtract 5 from both sides to get 2x = 10, then divide by 2.",
  },
  {
    id: "q-physics-1",
    topicId: "science-physics",
    prompt: "A runner travels 100 metres in 20 seconds. What is their speed?",
    options: ["2 m/s", "5 m/s", "20 m/s", "120 m/s"],
    answer: 1,
    explanation: "Speed is distance divided by time: 100 / 20 = 5 m/s.",
  },
  {
    id: "q-writing-1",
    topicId: "english-writing",
    prompt: "Which paragraph opening best supports a focused essay answer?",
    options: [
      "I am going to write about many things.",
      "This quote is interesting.",
      "The writer presents ambition as dangerous through Macbeth's changing choices.",
      "There are lots of techniques in the extract.",
    ],
    answer: 2,
    explanation: "It makes a clear point and links directly to the argument.",
  },
  {
    id: "q-cadets-1",
    topicId: "cadets-nav",
    prompt: "When reading a grid reference, which direction is read first?",
    options: ["Northings", "Eastings", "Contours", "Bearings"],
    answer: 1,
    explanation: "Grid references are read along the eastings first, then up the northings.",
  },
  {
    id: "q-football-1",
    topicId: "football-game",
    prompt: "Why scan before receiving the ball?",
    options: [
      "To slow the game down",
      "To decide the next action earlier",
      "To avoid passing",
      "To stay behind the defender",
    ],
    answer: 1,
    explanation: "Scanning gives you information before the ball arrives, so decisions are faster.",
  },
];
